# Generated by Django 5.2.1 on 2025-05-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('id_interconsulta', models.IntegerField()),
                ('evento', models.CharField(choices=[('Inciar', 'iniciar'), ('Referenciar', 'referenciar'), ('Revisar', 'revisar'), ('Priorizar', 'priorizar'), ('Agendar', 'agendar'), ('Atender', 'atender'), ('Terminar', 'terminar')], default='iniciar', max_length=11)),
                ('estado', models.CharField(choices=[('Enviado', 'enviado'), ('En Proceso', 'en_proceso'), ('Reintento', 'reintento'), ('Error', 'error')], default='en_proceso', max_length=10)),
                ('organizacion', models.CharField(max_length=255)),
                ('fecha_envio', models.DateTimeField()),
                ('intento', models.IntegerField()),
                ('fecha_recepcion', models.DateTimeField()),
                ('mensaje_resultado', models.TextField()),
            ],
        ),
    ]
