# Generated by Django 5.2.1 on 2025-06-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='id_interconsulta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='intento',
            field=models.IntegerField(default=1),
        ),
    ]
