# Generated by Django 5.2.1 on 2025-06-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_alter_mensaje_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True),
        ),
    ]
