# Generated by Django 5.2.1 on 2025-06-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_alter_mensaje_fecha_recepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
