# Generated by Django 5.2.1 on 2025-06-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_alter_mensaje_fecha_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='software',
            field=models.CharField(default='Otro', max_length=255),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('en_proceso', 'En Proceso'), ('reintento', 'Reintento'), ('error', 'Error')], default='en_proceso', max_length=10),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='evento',
            field=models.CharField(choices=[('iniciar', 'Iniciar'), ('referenciar', 'Referenciar'), ('revisar', 'Revisar'), ('priorizar', 'Priorizar'), ('agendar', 'Agendar'), ('atender', 'Atender'), ('terminar', 'Terminar')], default='iniciar', max_length=11),
        ),
    ]
