# Generated by Django 5.2.1 on 2025-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_mensaje_software_alter_mensaje_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='mensaje_resultado_error',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje_resultado',
            field=models.JSONField(default={}),
        ),
    ]
