# Generated by Django 5.2.1 on 2025-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_mensaje_mensaje_resultado_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje_resultado',
            field=models.JSONField(default=dict),
        ),
    ]
