# Generated by Django 5.2.1 on 2025-06-25 15:49

import sender.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0007_alter_mensaje_mensaje_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje_resultado',
            field=sender.models.RawJSONField(default=dict),
        ),
    ]
